### ISSUE TITLE
please make it public

### ISSUE THREAD

**Issue by HaohanWang** [MaheepChaudhary/causation_in_computer_vision#1]
Please make it public, like something like this: https://github.com/XindiWu/Awesome-Machine-Learning-in-Biomedical-Healthcare-Imaging 

move your review and comments here and get them viewed by others.

**Comment by MaheepChaudhary** [comment]
Thank you sir for the comment, I have made it public. 

Additionally, I will modify the Readme.md and will make it more professional and resourceful by taking the inspiration from Xindi's repo in some time.
